---
deployment:
      tasks:
        - export DEPLOYPATH=/home/occident/public_html/
        - /bin/cp index.html $DEPLOYPATH
        - /bin/cp Readme.txt $DEPLOYPATH
        - /bin/cp .htaccess $DEPLOYPATH
        - /bin/cp changelog.txt $DEPLOYPATH
        - /bin/cp inner-page.html $DEPLOYPATH
        - /bin/cp portfolio-details.html $DEPLOYPATH
        - /bin/cp -R .well-known
        - /bin/cp -R assets
        - /bin/cp -R forms
        - /bin/cp -R thumbnails

